#include <conio.h>
#include <iostream.h>
void main ()
{
  clrscr();
  cout << "aaaaaaaa ggggggggg uu uu"<<endl;
  cout << "aaaaaaaa ggggggggg uu uu"<<endl;
  cout << "aa   aa  gg        uu uu"<<endl;
  cout << "aa   aa  gg gggggg uu uu"<<endl;
  cout << "aaaaaaa  gg gggggg uu uu"<<endl;
  cout << "aa       gg     gg uu uu"<<endl;
  cout << "aa       ggggggggg uuuuu"<<endl;
  cout << "aa       ggggggggg uuuuu"<<endl;
  getch();
  }
